services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: ""
    startCommand: gunicorn main:app
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: PROVIDER_TOKEN
        sync: false
